### ISSUE TITLE
The land v0.8

### ISSUE THREAD

**Issue by deadhobos** [nathan/phosphorus#498] opened 2015-11-05 17:19 UTC
http://scratch.mit.edu/projects/75002902/
http://phosphorus.github.io/#75002902
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
the press any key script doesnt work

**Comment by tjvr** [comment] 2016-03-17 13:34
`key [any v] pressed` not implemented—duplicate of #503

**Closed** 2016-03-21 20:33 UTC
Labels: broken
