### ISSUE TITLE
mouse wheel

### ISSUE THREAD

**Issue by dzaima** [nathan/phosphorus#518] opened 2015-11-29 17:02 UTC
in the normal scratch player (not Stage3D) the mouse wheel up & down activates the up and down arrow key presses, but in phosphorus, it doesn't.
https://scratch.mit.edu/projects/89463594
if you scroll the mouse wheel it changes the cats position, but in phosphorus - no.
I'd love that to get added as that adds an easy scroll zoom.

http://scratch.mit.edu/projects/88749151/
http://phosphorus.github.io/#88749151
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 OPR/33.0.1990.115

**Comment by tjvr** [comment] 2016-03-17 14:26
Duplicate of #296

**Closed** 2017-01-15 12:17 UTC
