### ISSUE TITLE
Creature

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#334] opened 2015-02-26 09:21 UTC
The "main theme" sound of the "opening text" sprite is not played. The "breathing sound" of the Stage is played correctly instead.

http://scratch.mit.edu/projects/48787568/
http://phosphorus.herokuapp.com/#48787568
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by nathan** [comment] 2015-02-26 14:11
Duplicate of https://github.com/nathan/phosphorus/issues/333

**Closed** 2015-02-26 14:10 UTC
Labels: broken, duplicate
