### ISSUE TITLE
http://scratch.mit.edu/projects/45512912/

### ISSUE THREAD

**Issue by TipSpy** [nathan/phosphorus#310] opened 2015-02-04 16:34 UTC
lists do not work.......

http://scratch.mit.edu/projects/45512912/
http://phosphorus.herokuapp.com/#45512912
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:31.0) Gecko/20100101 Firefox/31.0

**Comment by nathan** [comment] 2015-02-04 17:44
Duplicate of https://github.com/nathan/phosphorus/issues/308

**Closed by nathan** 2015-02-04 17:44 UTC
Labels: broken
