### ISSUE TITLE
Audio not working and sprites issue

### ISSUE THREAD

**Issue by TheSecretPenguin** [nathan/phosphorus#736] opened 2016-12-29 14:36 UTC
Seems that audio does not run in projects, and certain sprites not closing when told to.

**Comment by Tymewalk** [comment] 2017-01-07 18:03
I've tested the audio glitch with several other projects. This happens on all of them.

Firefox 50.0 running on Ubuntu 14.04.

**Comment by TheSecretPenguin** [comment] 2017-01-08 08:50
Is there a way to fix the issue?

**Comment by nathan** [comment] 2017-01-15 06:18
Duplicate of #260

**Closed by nathan** 2017-01-15 06:18 UTC
