### ISSUE TITLE
Another Problem With Space Simulator 2

### ISSUE THREAD

**Issue by ScratcherAwesomeMinecraft2005** [nathan/phosphorus#738] opened 2016-12-29 19:13 UTC
http://scratch.mit.edu/projects/138105317/
http://phosphorus.github.io/#138105317
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:48.0) Gecko/20100101 Firefox/48.0

serious lag

**Comment by PortPixel** [comment] 2016-12-30 16:48
This is not an issue with phosphorus

**Comment by nathan** [comment] 2017-01-15 06:16
Duplicate of https://github.com/nathan/phosphorus/issues/737

**Closed by nathan** 2017-01-15 06:16 UTC
