### ISSUE TITLE
The lists won't work!

### ISSUE THREAD

**Issue by kittyhacker101** [nathan/phosphorus#336] opened 2015-03-03 15:54 UTC
I was trying to use lists in a project that was converted using phosphorus , but the lists won't show up in the project that was converted! 

Here's some more info : 
http://scratch.mit.edu/projects/49432226/
http://phosphorus.herokuapp.com/#49432226
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by nathan** [comment] 2015-03-03 18:42
Duplicate of https://github.com/nathan/phosphorus/issues/2

**Closed by nathan** 2015-03-03 18:42 UTC
