### ISSUE TITLE
Copying Text

### ISSUE THREAD

**Issue by mechwarrior11** [nathan/phosphorus#739] opened 2016-12-30 05:45 UTC
In on the Scratch website you're able to copy text in lists, but phosphorus doesn't even show lists so in my game I can't give a "save code" to the player if they use phosphorus rather than Scratch itself

**Comment by PortPixel** [comment] 2016-12-30 16:48
Phosphorus does not currently show lists, so if you want a save code you will have to use the Scratch Flash Player

**Comment by PortPixel** [comment] 2017-01-14 10:49
Phosphorus does not show lists, so you will have to find a different way to generate save codes if you need to.

**Comment by nathan** [comment] 2017-01-15 06:06
Duplicate of https://github.com/nathan/phosphorus/issues/2

**Closed by nathan** 2017-01-15 06:06 UTC
Labels: duplicate
